[package]
name = "argot"
version = "0.1.0"
authors = ["Steven Hanna <steventhanna@gmail.com>"]

[dependencies]
simple-error = "0.1"
clap = "2.32.0"
walkdir = "2"
glob = "0.2"
indicatif = "0.10.2"
human-panic = "1.0.1"
